haskell/Test: ftest distinguishes error exit and success with bad output
We do this by storing the output of the test run in a file under .build/;
this is fine because it gives us something we can go back to for further
analysis in case there's a complex failure.

diff --git a/haskell/Test b/haskell/Test
--- a/haskell/Test
+++ b/haskell/Test
@@ -16,7 +16,10 @@ stack test --ta "$*" || die 1 "Unit tests"
 echo
 
 echo '───── Functional Tests'
-stack run ml-tableau -- < ftest/1.input | diff -u ftest/1.expected - \
+mkdir -p .build/test/
+stack run ml-tableau -- < ftest/1.input > .build/test/1.output \
+    || die 2 "ml-tableau error: exit code = $?"
+diff -u ftest/1.expected .build/test/1.output \
     || die 1 "ml-tableau produced unexpected output"
 
 echo 'PASSED'
